# Server Port (Java runs on 8080)
server.port=8080

# Allow huge Base64 strings (50MB Limit)
server.tomcat.max-http-post-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=50MB

# Pretty print JSON responses (Optional, makes debugging easier)
spring.jackson.serialization.indent_output=true